# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs

orbs:
  node: circleci/node@5.0.2

jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - node/install-packages:
          cache-only-lockfile: true 
          check-cache: never 
          include-branch-in-cache-key: true 
          pkg-manager: npm 
          with-cache: true 
          app-dir: src 

workflows:
  example-workflow:
    jobs:
      - example-job